<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interface\**" />
    <EmbeddedResource Remove="Interface\**" />
    <None Remove="Interface\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Dependencies" Version="6.0.553" />
  </ItemGroup>

</Project>
